### ISSUE TITLE
@type named identifier breaks aws-elixir

### ISSUE THREAD

**Issue by Doerge** [aws-beam/aws-codegen#114]
The generated @types names are not properly sanitized. With the type name `identifier` aws-elixir fails to build for the latest `quicksight` from aws go sdk. Either it should be added like this, or the other path should be used. It's unclear to me why there are two paths, and what's the best option:
https://github.com/aws-beam/aws-codegen/pull/113/commits/dc18ee4fecd40110e631a06c60e37cb0e0a27871

**Comment by onno-vos-dev** [comment]
@Doerge Somehow I missed this... I blame summer 🙈 Should be sorted now.
