### ISSUE TITLE
Migrate from jsx to jsone

### ISSUE THREAD

**Issue by jfacorro** [aws-beam/aws-codegen#19]
There is a suggestion from @mrallen1 to migrate the Erlang client from using `jsx` to using `jsone`. I'm creating this ticket so we can discuss the migration here and close #6.

**Comment by onno-vos-dev** [comment]
Going to decline this as I don't see why we should migrate from jsx to jsone. Unless strong reasons are presented, I do not see why all users of aws-erlang should change their dependency. 

Trying to do some spring cleaning on our issues.
