### ISSUE TITLE
Mechanical Turk API is not regionalised but has no `credentialScope` for `aws-global`

### ISSUE THREAD

**Issue by jfacorro** [aws-beam/aws-codegen#40]
The Mechanical Turk API is not regionalized but doesn't include information for `aws-global`, it has an entry for `sandbox` instead (from `endpoints.json`):
```
      "mturk-requester" : {
        "endpoints" : {
          "sandbox" : {
            "hostname" : "mturk-requester-sandbox.us-east-1.amazonaws.com"
          },
          "us-east-1" : { }
        },
        "isRegionalized" : false
      },
```
This special case needs to be addressed in the generation somehow.

**Comment by onno-vos-dev** [comment]
I believe this was fixed a long time ago. If not looking at: https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/mturk.json#L2815-L2822 it should be fixed now since the move to v2 spec.
