### ISSUE TITLE
Issues producing Edoc for some of the generated modules

### ISSUE THREAD

**Issue by robertoaloi** [aws-beam/aws-codegen#72]
Producing `edoc` fails for a couple of modules. Examples of invalid generated docstrings are:

From `aws_chime.erl`:
```
%% == Functionality & restrictions ==
```

From `aws_forecast.erl`:
```
%% `<ExportJobName>_<ExportTimestamp>_<PartNumber>.csv'
```

From `aws_route53.erl`:
```
-%% table. These characters include the following: `! " # $ % & ' ( ) * + , -'
```

From `aws_codestar_connections.erl`:
```
%% A host created through the CLI or the SDK is in `PENDING` status by
```

These errors are verified on the Erlang side. Not sure if the Elixir side is also affected, too.

**Comment by onno-vos-dev** [comment]
Stale issue and should be solved by now 👍👌
