### ISSUE TITLE
Update base repository for the `aws-beam` projects

### ISSUE THREAD

**Issue by robertoaloi** [aws-beam/aws-codegen#75]
The `aws-codegen`, `aws-erlang` and `aws-elixir` repos are forks of the respective `jkakar/*` versions.
Nowadays, the `jkakar`repos are outdated and they point to `aws-beam` from their respective READMEs.
The current setup is suboptimal since, whenever a PR is raised in one of the `aws-beam` repositories, `jkakar` is marked as the default "base repository":

![Screenshot 2021-03-24 at 13 25 14](https://user-images.githubusercontent.com/91769/112310038-66135400-8ca4-11eb-8cd2-3d99b88e9f7d.png)

I contacted GitHub support to check if there is an option to update the base repo, to make contributors life easier. They gave the following two options:

1. We can extract your forks from the current repository network. This will leave the repositories owned by jkakar as root repositories, but the aws-beam repositories and the child repositories under them would be moved to their own network where the aws-beam repositories are the root. I can do this with just your confirming that this is what you want to do.

2. We can update the current repository network so that the aws-beam repositories become the root repository for the network and the ones owned by jkakar would become children of those repos. This would leave all repositories currently under the jkakar repositories in the same fork network, but would require permission from jkakar to make the change.

Of course we also have option 3. which is leaving things as they are.

@jkakar @philss Any opinions?

**Comment by jkakar** [comment]
I have a slight preference for #2, just because I'd like to keep my repositories in the same network. What do I need to do to make that happen?

**Comment by philss** [comment]
@robertoaloi I don't have a strong opinion on this. I'm OK with both :+1:

**Comment by robertoaloi** [comment]
Let's go for 2, then. @jkakar I will contact you privately on what's needed from you.

**Comment by robertoaloi** [comment]
Fixed!

**Comment by jkakar** [comment]
Thanks for taking care of this Roberto!
